### ISSUE TITLE
Use GitHub releases interface for releases

### ISSUE THREAD

**Issue by jsstevenson** [ga4gh/vrs-python#109]
Currently, the [action](https://github.com/ga4gh/vrs-python/blob/main/.github/workflows/release.yml) to push a release to PyPI is triggered by appending a semver-like tag to a commit. This means that the closest thing to a changelog is the tag history, which lacks information like release notes, let alone more significant information like breaking change notifications. 

The GitHub release interface makes it easy to append release notes (it can also autogenerate a list of changes based on commit messages, which is typically more than sufficient especially if [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) are ~adhered to). See the [Variation Normalizer](https://github.com/cancervariants/variation-normalization/releases
) release log for a good example. It also creates a handy link to the diff.

I'm not sure that this would necessarily require any changes to the release action (you can make a new tag as part of making a GH release) -- it does mean a change in workflow on the part of the maintainers, but personally, it'd be helpful to me (an occasional user) to have access to a more descriptive change list.

**Comment by korikuzma** [comment]
Also in favor

**Comment by korikuzma** [comment]
@ga4gh/vrs-python-maintainers I made a release on GH with the current workflow and it worked fine! We can switch 

```yaml
on:
  push:
    tags:
      - "*.*.**"
```

to

```yaml
on:
  release:
    types: [created]  # or published
```

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release

**Comment by korikuzma** [comment]
@ga4gh/vrs-python-maintainers another reason why we should use GH releases is because it creates a zenodo version.

**Comment by jsstevenson** [comment]
@korikuzma now that we've talked this over as a group, I think we can close this?

**Comment by korikuzma** [comment]
@jsstevenson yup, closing
