### ISSUE TITLE
Update `ga4gh_identify` to take the `ordered` property into consideration

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/vrs-python#116]
@ahwagner added an `ordered` property in the VRS schemas for array fields. @ahwagner can you comment more on this field?

**Comment by ahwagner** [comment]
Yes: the `ordered` property of an `array` indicates whether order is meaningful in an array (e.g. in a `ComposedSequenceExpression`) or not meaningful (e.g. in a `Genotype`). If `ordered == True`, then the array elements MUST NOT be sorted during serialization; conversely if `ordered == False`, then the array elements MUST be sorted during serialization.

**Comment by korikuzma** [comment]
Re-opening for 2-alpha
