### ISSUE TITLE
Create online notebook welcome text

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs-python#128]
Put the getting started / mybinder / dataproxy info in a shared location for use across all notebooks.

This may be implemented as a common helper function import, and/or a brief link back to a single markdown document.

**Comment by korikuzma** [comment]
@wesleygoar was assigned this during the last connect touchbase meeting

**Comment by korikuzma** [comment]
@toneillbroad added [this](https://github.com/ga4gh/vrs-python/tree/main/notebooks/getting_started). I think we can close.
