### ISSUE TITLE
Add support for protein variation in translate_to()

### ISSUE THREAD

**Issue by jarbesfeld** [ga4gh/vrs-python#133]
translate_to() currently supports translation to HGVS strings for nucleic acid variation but not protein variation

**Comment by korikuzma** [comment]
This issue will also be helpful for our VarCat project. Given gnomad vcf representation, we use the VICC Variation Normalizer to translate to the VRS Object on the protein sequence. We need to be able to get the protein hgvs expression from this.

**Comment by korikuzma** [comment]
@jarbesfeld is this needed or can we close?

**Comment by jarbesfeld** [comment]
@korikuzma I think this can be closed for now. I had opened this issue for the MAVE work, but was able to write a custom protein hgvs translator

**Comment by korikuzma** [comment]
@jarbesfeld It might be nice for you to move this over to VRS-Python at some point.

**Comment by jsstevenson** [comment]
if it would be nice to move over then maybe this should be an open issue?
