### ISSUE TITLE
Add input validation for _from_gnomad

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/vrs-python#147]
I made a [similar issue](https://github.com/ga4gh/vrs-hackathons/issues/7) for translator validation in our hackathon repo. 

`7-7-helloworld-T` is not a valid gnomAD VCF, but we're still able to translate to a VRS Allele as seen below:

![Screen Shot 2023-01-13 at 9 23 12 AM](https://user-images.githubusercontent.com/42851808/212342121-f05ad0f3-cea1-4392-a675-a87f3f2aea08.png)

We should add some additional validation checks for the input

**Comment by korikuzma** [comment]
@ahwagner In the notebooks, I saw this description:

![Screen Shot 2023-01-16 at 10 21 34 AM](https://user-images.githubusercontent.com/42851808/212712652-227996a1-6f10-4a57-af7f-f5921a06f3c5.png)

I'm now wondering if we should provide a parameter on whether or not to do validation rather than always requiring valid input.

**Comment by ahwagner** [comment]
I think we should check and throw a warning. If somebody provides a reference nucleotide for translation, and that reference does not match the sequence and location provided, it is an indication something may be wrong in their workflow. I think it is okay to parameterize this check if people want to suppress that behavior, but I think it should be active by default.
