### ISSUE TITLE
Consider expanding issue labels

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/vrs-python#170]
[These](https://gist.github.com/korikuzma/9a5b24fdb2014ec33039e983407390b7) are labels we use in our other repos. I think it would be nice to expand the labels we use in this repo. @ga4gh/vrs-python-maintainers  @ga4gh/vr-maintainers What are your thoughts?

**Comment by larrybabb** [comment]
@korikuzma please proceed with applying these labels if you find them useful. If you don't care that much then you can close this. You and Kyle will be the primary beneficiaries of these labels for the immediate future

**Comment by korikuzma** [comment]
@larrybabb I'll go ahead and make time to update them next week!

**Comment by korikuzma** [comment]
Done. @ga4gh/vr-maintainers @ga4gh/vrs-python-maintainers Feel free to update issues with tags
