### ISSUE TITLE
Error when building mybinder 

### ISSUE THREAD

**Issue by SalemBajjali** [ga4gh/vrs-python#175]
I was trying to build https://mybinder.org/v2/gh/ga4gh/vrs-python/main, but it doesn't seem to be working.

**Comment by korikuzma** [comment]
@SalemBajjali Fixed in #176 for the main branch. We'll want to also fix in:
- [ ] 0.9 branch
- [ ] 0.8 branch

**Comment by korikuzma** [comment]
Made PRs from cherry-picked commits from @SalemBajjali & @ahwagner . We can close when these are merged
