### ISSUE TITLE
Python CQA should run python 3.10

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/vrs-python#183]
In the Makefile, we specify python 3.10. So we should update GitHub actions below
https://github.com/ga4gh/vrs-python/blob/1600b271064eef57a86f7d40c02aaca8d19d9f61/.github/workflows/python-cqa.yml#L20

**Comment by aniketh3014** [comment]
I have updated python-version to 3.10 in python-cqa.yml.
Should I make a pull request?

**Comment by korikuzma** [comment]
Going to update in #199
