### ISSUE TITLE
VRS-demo-notebooks on Terra not accessible

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vrs-python#189]
In the read me it says

> We have created a public [VRS-demo-notebooks](https://app.terra.bio/#workspaces/terra-outreach/VRS-demo-notebooks) workspace in Terra that contains the demo notebooks along with instructions for running them with minimal setup. To get started, see either the [VRS-demo-notebooks](https://app.terra.bio/#workspaces/terra-outreach/VRS-demo-notebooks) workspace or the [Terra.ipynb](https://github.com/ga4gh/vrs-python/blob/main/notebooks/Terra.ipynb) notebook in this repository.

When I tried this Terra said that I don't have access and need to get permission to be added to the authorization domain.  

Is this expected behavior? If so, who do I request access from ? If not, can we figure out how to get this working again?

**Comment by ahwagner** [comment]
@vdauwera please help!

**Comment by vdauwera** [comment]
Got a response from Terra support, someone on their end needs to approve making the workspace public -- will keep pushing on this. Tbh I'm surprised because I thought it was public already. Unfortunately I can't look at the original email thread since my Broad account is gone.

**Comment by vdauwera** [comment]
I think this should be resolved now, pls check and confirm?

**Comment by larrybabb** [comment]
Yes. The notebook is accessible now. Thank you.

**Comment by korikuzma** [comment]
@larrybabb can we close the issue?
