### ISSUE TITLE
pip install ga4gh.vrs[extras] returns "no matches found"

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vrs-python#190]
> pip install ga4gh.vrs[extras]
returns
> no matches found: ga4gh.vrs[extras]
any help would be appreciated.

**Comment by korikuzma** [comment]
@larrybabb If you're using zsh try `pip install 'ga4gh.vrs[extras]'`

**Comment by korikuzma** [comment]
Done in #207 , #208, #209
