### ISSUE TITLE
Upgrade core.ga4gh_serialize.dictify to use schema ga4gh.defs vs current "_" logic to generate digest

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vrs-python#193]
1. Replace pythonjsonschemaobjects tool in core by using https://github.com/koxudaxi/datamodel-code-generator/ to generate the pydantic classes which can be manually modified (for the short term).

2. Create the functions needed to generate the digest from the required fields in the ga4gh.defs attribute of the schema thus replacing the current "_" attribute prefixed approach.

**Comment by theferrit32** [comment]
Recommending closing as completed. 

See `ga4gh_serialize` updates referred to here: https://github.com/ga4gh/vrs-python/issues/195#issuecomment-1662786836

**Comment by korikuzma** [comment]
> Recommending closing as completed.
> 
> See `ga4gh_serialize` updates referred to here: [#195 (comment)](https://github.com/ga4gh/vrs-python/issues/195#issuecomment-1662786836)

This is complete. Closing
