### ISSUE TITLE
Upgrade digester logic to use new schema 'ga4gh.defs' approach

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vrs-python#195]
Create the functions needed to generate the digest from the required fields in the ga4gh.defs attribute of the schema thus replacing the current "_" attribute prefixed approach.

**Comment by theferrit32** [comment]
Implemented in `2-alpha` branch. 

Definition in model class:
https://github.com/ga4gh/vrs-python/blob/57340e85fc45763fe66d9633d3cba5b208c8477d/src/ga4gh/vrs/_internal/models.py#L365-L373

Use in serialize function:
https://github.com/ga4gh/vrs-python/blob/57340e85fc45763fe66d9633d3cba5b208c8477d/src/ga4gh/core/_internal/identifiers.py#L202
