### ISSUE TITLE
Annotation Data

### ISSUE THREAD

**Issue by nit-ram-36** [ga4gh/vrs-python#197]
Is VRS the right format to include variant annotation data (e.g. ClinVar annotation)? Otherwise, which GA4GH format should be used for this purpose? Also, is it possible to describe multiple variants with VRS format?

**Comment by korikuzma** [comment]
Hi @nit-ram-36 . Sorry for the delayed response. For annotation data, I would recommend [va-spec](https://github.com/ga4gh/va-spec). 

We do have some models in VRS 1.3.x for representing multiple variations.
- [Haplotypes](https://vrs.ga4gh.org/en/1.3/terms_and_model.html#haplotype) - specific combination of Alleles that are in-cis: occurring on the same physical molecule
- [Genotype](https://vrs.ga4gh.org/en/1.3/terms_and_model.html#genotype) - representation of the variants present at a given genomic locus, and may be referred to either by individual nucleotide representations
- [VariationSet](https://vrs.ga4gh.org/en/1.3/terms_and_model.html#variationset) - Sets of variation are used widely, such as sets of variants in dbSNP or ClinVar that might be related by function.

@ahwagner and @larrybabb are working on designing VRS 2.0-alpha, so there may be some changes.

**Comment by ahwagner** [comment]
Hi @nit-ram-36. VRS is a good foundation for describing complex variation concepts seen in annotation resources like ClinVar. The GA4GH VR team is currently working on a Categorical Variation specification that uses VRS and other vocabularies to formalize these variants.

An early implementation of this specification was used in our [VRSATILE](https://github.com/ga4gh/vrsatile/tree/gk-pilot) spec. Examples of this applied to ClinVar may be found in [ga4gh/gk-pilot](https://github.com/ga4gh/gk-pilot/tree/2-alpha).
