### ISSUE TITLE
Python versions to support

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/vrs-python#199]
In `setup.cfg` we specify `python_requires = >= 3.6`. I think we should change to `python_requires = >= 3.8` since 3.7 end-of-life was 6 days ago. We should also add 3.11 to CI checks. @ga4gh/vrs-python-maintainers do you agree?

**Comment by korikuzma** [comment]
@ga4gh/vr-maintainers

**Comment by ahwagner** [comment]
Yes, this sounds good to me.

**Comment by larrybabb** [comment]
good with me too

**Comment by aniketh3014** [comment]
Hey @korikuzma, the changes that I made in my last commit in #198, were correct, or I still got it wrong?

**Comment by korikuzma** [comment]
@aniketh3014 is what we need now:

https://github.com/ga4gh/vrs-python/blob/536bb1c7f9d5582091bcf657813f8cb8437dda20/.github/workflows/python-cqa.yml#L20

Decided to just do one PR since I think it's cleaner

**Comment by aniketh3014** [comment]
@korikuzma Thank you for taking the time to clarify and guide me through. I am trying to understand the code base and learn the technologies used, I truly appreciate your support.

**Comment by korikuzma** [comment]
@aniketh3014 Feel free to make new issues if you have questions. We have some issues with the label `good first issue` if you'd like to tackle some other problems.
