### ISSUE TITLE
Repo cleanup

### ISSUE THREAD

**Issue by jsstevenson** [ga4gh/vrs-python#223]
For example:

- `TODO`: This file seems duplicative and potentially confusing -- maybe any remnant tasks should be made into new GH issues and it can be removed from tracking?
- Travis CI?

**Comment by korikuzma** [comment]
Can we make this a general issue about removing old (potentially confusing) files?

**Comment by jsstevenson** [comment]
@korikuzma MANIFEST.in ? https://github.com/ga4gh/vrs-python/blob/main/MANIFEST.in

**Comment by korikuzma** [comment]
@jsstevenson we no longer use VRSATILE submodule
