### ISSUE TITLE
Update references to model __fields__

### ISSUE THREAD

**Issue by theferrit32** [ga4gh/vrs-python#243]
``
vrs-python/src/ga4gh/vrs/_internal/models.py:111: PydanticDeprecatedSince20: The `__fields__` attribute is deprecated, use `model_fields` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.1.1/migration/
``

**Comment by theferrit32** [comment]
So right now `Allele.model_fields == Allele.__fields__`. So we can just literally replace it with the new class property name.

**Comment by theferrit32** [comment]
Implemented in [a21cdc2](https://github.com/ga4gh/vrs-python/commit/a21cdc2f57f71cef4cbb33b508e0ec5031d6c3bd)

**Comment by korikuzma** [comment]
Re-opening. This is still in tests/validation/test_vrs_schema.py
