### ISSUE TITLE
Update readme for running notebooks

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/vrs-python#267]
we set python version to 3.10 in the makefile, but readme says to use 3.7. 

we should also provide some information on how to run inside VS Code (sometimes the kernel is not selected)

**Comment by manish0kuniyal** [comment]
Hi ,I'm interested in solving this issue. Can I be assigned this task?

**Comment by manish0kuniyal** [comment]
Thank you,
I was going through the README and noticed a couple of things:
Under the "Testing" heading, it mentions "usingsmoketest" and requires Python version 3.8+. Is it alright to update this to Python version 3.10?
I've observed that sometimes the Python interpreter isn't selected in the bottom right corner of VS Code. Would it make sense to add a subheading under "Running the Notebooks on the Terra platform" to address this issue?

Just looking for some clarification on these points. Please let me know if this aligns with the requirements. 
Thanks for your help.

**Comment by korikuzma** [comment]
@manish0kuniyal 

>Under the "Testing" heading, it mentions "usingsmoketest" and requires Python version 3.8+. Is it alright to update this to Python version 3.10?

I think you're looking at the vrs repo for smoke tests. This issue is for vrs-python

>I've observed that sometimes the Python interpreter isn't selected in the bottom right corner of VS Code. Would it make sense to add a subheading under "Running the Notebooks on the Terra platform" to address this issue?

Yes, creating a "Running the Notebooks with VS Code" section sounds great!

**Comment by manish0kuniyal** [comment]
The required changes have been made. Please review. If there are any additional changes needed, feel free to contact.
