### ISSUE TITLE
Regular expression validation for gnomad format should allow more letters

### ISSUE THREAD

**Issue by mingjiecn** [ga4gh/vrs-python#275]
Right now for gnomad_re(https://github.com/ga4gh/vrs-python/blob/593508c6e8229336ca1f53a06f69966020cd68f7/src/ga4gh/vrs/extras/translator.py#L44C3-L44C3), it only allows those Nucleotide symbol:ACGTN. But there are more symbols such as R, Y, K, M, S, W. See all the symbols here: [gnomad_reregular expression validation](https://www.hgmd.cf.ac.uk/docs/nuc_lett.html). Because of the limited symbols, I am not able to generate certain SPDIs from the gnomad format. For example: SPDI `NC_000017.11:83129587:TTGWCACATGATTG:TTG`  from gnomad format `17-83129587-GTTGWCACATGA-G`, and SPDI `NC_000003.12:16894810:W:` from gnomad format `3-16894810-TW-T`

**Comment by korikuzma** [comment]
@mingjiecn I had previously updated the regex in #148 based on the [VCF Specification](https://samtools.github.io/hts-specs/VCFv4.4.pdf)

<img width="830" alt="Screenshot 2023-11-07 at 5 34 35 PM" src="https://github.com/ga4gh/vrs-python/assets/42851808/a7d7cd30-76b8-47c0-ab5b-7a03714a61e1">

I haven't seen any other characters outside of (ACGTN) in gnomad VCF like expressions. @wesleygoar @ga4gh/vr-maintainers  @ga4gh/vrs-python-maintainers Are the other characters that @mingjiecn listed valid for gnomad VCF expressions? If so, I'll go ahead and make this change.

**Comment by korikuzma** [comment]
I do see these characters in the reference sequence. I'll go ahead and make a PR.

**Comment by korikuzma** [comment]
@mingjiecn Created #276 for a fix. Thanks for pointing this out.

**Comment by mingjiecn** [comment]
Thanks for the fast response. Now waiting for the merge and can't wait to use it! @korikuzma

**Comment by korikuzma** [comment]
@mingjiecn Hi, here is the latest release: https://pypi.org/project/ga4gh.vrs/0.8.5/ . Thanks again for making this issue!
