### ISSUE TITLE
Remove stale action

### ISSUE THREAD

**Issue by jsstevenson** [ga4gh/vrs-python#287]
As far as I can tell, the stale action has not, at least in recent years, actually closed an issue -- all closures have been manual (mostly by @korikuzma and @theferrit32). On the flip side, we've currently marked almost every open issue as `stale-exempt`. Is this action still a useful part of the workflow? Would it make sense to at least alter the configuration (maybe lengthen `days-before-issue-stale`) if not remove it entirely?

**Comment by korikuzma** [comment]
I'm pro removing it. I think that since we are constantly switching between projects, that this does not make sense for the current @ga4gh/vrs-python-maintainers .

**Comment by ahwagner** [comment]
Who am I to argue with our @ga4gh/vrs-python-maintainers? Remove it. 👍
