### ISSUE TITLE
Change order in the readme

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/vrs-python#291]
>It says "once installed as described above" but this venv and the directory layout `venv/<version>` is created in the makefile. The makefile step `make devready` is below in `Installing for development`. Maybe before the pip install above we should add a step about creating a virtual environment with `python3.10 -m venv venv/3.10`, or add it to this section. 
>
>Should we also put a note that Python 3.10 must be installed? The makefile won't run otherwise.
>
>(I have mixed opinions on tying the makefile to a python version)

_Originally posted by @theferrit32 in https://github.com/ga4gh/vrs-python/pull/288#discussion_r1401104187_

**Comment by larrybabb** [comment]
Fixed in PR #376
