### ISSUE TITLE
VCFAnnotator adds an error message in an INFO field for sites where VRS ID computation fails

### ISSUE THREAD

**Issue by ehclark** [ga4gh/vrs-python#297]
When VRS computation for a site fails in `VCFAnnotator.annotate()`, the method raises an exception.  It would be preferable for the error to be caught and an error INFO field added to the VCF site.  This will allow the caller to determine how to handle failures and retain the VRS IDs that can be successfully computed.

**Comment by korikuzma** [comment]
@ehclark can you explain this a little further? Currently, the annotator logs errors when `_from_gnomad` raises an exception.

**Comment by ehclark** [comment]
@korikuzma I want to accomplish 2 things:

1. When VRS ID computation fails for a VCF site, an error message is placed in the output VCF so that the consumer knows affirmatively that an error occurred.  That will allow us to build triage/monitoring features into the consumer system.
2. If an unexpected error occurs processing a VCF site, VRS ID computation for other sites is able to proceed and be returned.  VCF files often have unexpected content that can break code and we will be processing VCF files that originate from many sources.

The main change will be to enclose the VCF site processing code in a try/except:
```python
try:
    vrs_field_data = self._get_vrs_data(
        record, vrs_data, assembly, additional_info_fields, vrs_attributes,
        output_pickle, output_vcf, compute_for_ref, compute_for_alts
    )
except Exception as ex:
    #  ...add error message to VCF...
```

Also, while it is true that `VCFAnnotator._get_vrs_object()` logs errors, in the AnyVar usage, the `_get_vrs_object()` method is overridden and it suppresses exceptions (and looks like it does not log errors either?).  So I will also change this as well so that exceptions propagate up to the top-level try/except at the VCF site level.
