### ISSUE TITLE
Update PostgreSQL information in the readme

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/vrs-python#307]
From discussion on #306 , I think we should include which PostgreSQL versions(s) are supported and an additional option on how to install PostgreSQL via homebrew in the readme

**Comment by manish0kuniyal** [comment]
Added additional details for Homebrew installation and linked the documentation.
![image](https://github.com/ga4gh/vrs-python/assets/110035752/04b5efea-b0e6-403c-a745-83a25f3c071a)

There is a Minor formatting error which has also been addressed in this commit.
     ![image](https://github.com/ga4gh/vrs-python/assets/110035752/695d7a44-b9f1-4674-86b6-c46e2f5c257f)

**Comment by korikuzma** [comment]
@sivangbagri I don't think this is needed. There is already work done for this that I just need to cherry-pick
