### ISSUE TITLE
Reference setup help docs in readme

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/vrs-python#308]
From discussion on #306 , we should reference [setup help docs](https://github.com/ga4gh/vrs-python/tree/main/docs/setup_help) in the readme. People may not be aware of these docs

**Comment by larrybabb** [comment]
@korikuzma whatever happened to this? It seems like we dropped the work from #306 at some point. Was that on purpose or did it not get pulled forward at any point?

**Comment by korikuzma** [comment]
@larrybabb that was on purpose. I condensed it and cleaned it up a lil. This issue is complete and was part of #376
