### ISSUE TITLE
`VCFAnnotate.annotate` cannot reliably read from and write to VCF

### ISSUE THREAD

**Issue by quinnwai** [ga4gh/vrs-python#340]
**Environment**: MacOS Ventura 13.2.1, Python 3.8.3, VRS-Python 2.0.0a2

**Steps to Reproduce**
- Get input VCF `https://github.com/pcingola/SnpEff/blob/master/examples/test.chr22.vcf`
```
from ga4gh.vrs.extras.vcf_annotation import VCFAnnotator

stem="test.chr22"
input_vcf = f"{stem}.vcf"
output_vcf = f"{stem}.vcf.gz"
output_pkl = f"{stem}-vrs-objects.pkl"

vcf_annotator = VCFAnnotator("~/seqrepo/latest")
vcf_annotator.annotate(input_vcf, output_vcf, output_pkl) 
```

**Expected Results**
Outputted VCF with annotated VRS_IDs and pickle file containing VRS objects

**Actual Results**

> ValueError: invalid file `b'test.chr22.vcf'` (mode=`b'r'`) - is it VCF/BCF format?

A manual fix to this is adding a file format header to the VCF (##fileformat=VCFv4.2) but this causes
> [W::vcf_parse] Contig '22' is not defined in the header. (Quick workaround: index the file with tabix.)
> [E::vcf_format] Invalid BCF, CONTIG id=0 not present in the header
> ...
> OSError: [Errno 22] b'Invalid argument'

I can get the `annotate` function outputting a pickle if I don't specify an output VCF, but I have some future use cases where I'd need that annotated VCF as well.

**Comment by korikuzma** [comment]
Hi @quinnwai . I'm looking at the [VCF 4.2 spec](https://samtools.github.io/hts-specs/VCFv4.2.pdf). In addition to the File Format (1.2.1) you will also need to the Contig field format (1.2.7) which would begin with `##contig=<ID=22,`. After adding these, I was able to run the code without those warnings. 

Your current code will output both a pickle and annotated vcf. I don't think I am following your last statement. Could you explain?

**Comment by quinnwai** [comment]
Hey @korikuzma! Thanks for pointing me to this, I was hoping that the annotate method could accept the many instances of "partially compliant" VCFs in the wild, especially when it comes to headers. Addressing your question, my use case involves processing many of those VCFs so it would be difficult for me to rely on manual labeling of VCFs as they come in.

If possible, I would like to suggest that more informative error messages be included so users can identify and resolve issues efficiently. For instance, providing alternative validators or validation methods to enhance the robustness of the client's VCF file processing. Hopefully, this could potentially reduce the filing of similar issues to both reduce support needs and provide users with more reliable results!

**Comment by korikuzma** [comment]
@quinnwai I don't work with VCFs, but I'll share my thoughts. 

>I was hoping that the annotate method could accept the many instances of "partially compliant" VCFs in the wild, especially when it comes to headers. 

Personally, I don't think VRS-Python should be validating or resolving incomplete VCFs. I think it should be on the user to provide a proper VCF. For example, the metadata information would not be known to VRS-Python. If VRS-Python were to add this information, it would be pretty generic and I'm not sure it would adequately describe the VCF. 

>my use case involves processing many of those VCFs so it would be difficult for me to rely on manual labeling of VCFs as they come in

I would recommend creating a script to add the header information rather than manually doing this.

>If possible, I would like to suggest that more informative error messages be included so users can identify and resolve issues efficiently. For instance, providing alternative validators or validation methods to enhance the robustness of the client's VCF file processing

The warning and error messages come from [pysam](https://github.com/pysam-developers/pysam), so I would recommend raising an issue there if you think they could be improved.

**Comment by quinnwai** [comment]
Hi @korikuzma, thanks for the clarification. Makes sense that it would be a lot of scope to validate VCFs in vrs-python, didn't mean to assume that would be easy or necessary. I think what I'll have to focus on is how well Pysam is able to support different VCFs vs pyVCF or other VCF parsers. Appreciate the help!

**Comment by korikuzma** [comment]
@quinnwai no worries! Pysam was used in the initial implementation, so I stuck with it. If you find that an alternate package is better, I think we’d be open to switching if it aligns with VRS-Python’s needs.

**Comment by korikuzma** [comment]
Closing this since VRS-Python will not do VCF validation for the time being.
