### ISSUE TITLE
Standardize serialize behavior for SequenceReference

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs-python#341]
Currently, SequenceReference is digested while other (non-identifiable) Value Objects are not. This should be updated so that SequenceReference behaves as a standard Value Object (see model 2 from discussion ga4gh/vrs#465).

**Comment by korikuzma** [comment]
@ahwagner can we close this since you addressed in #342?

**Comment by ahwagner** [comment]
Yes!
