### ISSUE TITLE
‘NoneType’ object has no attribute ‘root’ when getting HGVS from Python dict

### ISSUE THREAD

**Issue by quinnwai** [ga4gh/vrs-python#344]
I’m trying to get an hgvs ID from a python dict, but I’m running into problems when it does validation of `vo.state.sequence.root`, here’s the code I’m using…

```
allele = models.Allele(**allele_dict)
_id = translator.translate_to(allele, fmt)
```

what the allele_dict looks like…

```
{
  "id": "ga4gh:VA.VzxoidAEEbcLu12HOOxUYo4fuXE4A5iv",
  "type": "Allele",
  "location": {
    "id": "ga4gh:SL.fM4OgBuELjPWKeQSCjVKdcTJvas-H5uH",
    "type": "SequenceLocation",
    "sequenceReference": {
      "type": "SequenceReference",
      "refgetAccession": "SQ.vWwFhJ5lQDMhh-czg06YtlWqu0lvFAZV"
    },
    "start": 262338,
    "end": 262339
  },
  "state": {
    "type": "ReferenceLengthExpression",
    "length": 410,
    "repeatSubunitLength": 409
  }
}
```

and the error:
> File ~/.local/lib/python3.10/site-packages/ga4gh/vrs/extras/translator.py:144, in Translator.translate_to(self, vo, fmt)
>     142 “”"translate vrs object `vo` to named format `fmt`“”"
>     143 t = [self.to](http://self.to/)_translators[fmt]
> --> 144 return t(vo)
> File ~/.local/lib/python3.10/site-packages/ga4gh/vrs/extras/translator.py:523, in AlleleTranslator._to_hgvs(self, vo, namespace)
>     518         start += 1
>     519     ival = hgvs.location.Interval(
>     520         start=hgvs.location.SimplePosition(start),
>     521         end=hgvs.location.SimplePosition(end)
>     522     )
> --> 523     alt = str(vo.state.sequence.root) or None  # “” => None
>     524     edit = hgvs.edit.NARefAlt(ref=ref, alt=alt)
>     526 posedit = hgvs.posedit.PosEdit(pos=ival, edit=edit)
> AttributeError: ‘NoneType’ object has no attribute ‘root’

Would love to know how to fix this, thanks!

**Comment by korikuzma** [comment]
Quick comment: I think we only have tests that use Literal Sequence Expressions for to_hgvs.

**Comment by quinnwai** [comment]
For reference, I pulled the data from [AnVIL Data Explorer](https://explore.anvilproject.org/files?filter=%5B%7B%22categoryKey%22%3A%22files.file_format%22%2C%22value%22%3A%5B%22.vcf%22%5D%7D%5D), using the file 
`HG006vCHM13_20200921_mm2_PBCCS_sniffles.s2l20.refined.nSVtypes.ism.vcf`

 I had to manually edit the INFO header's description for `INTRALIST_SAMPLES` from "." to '.' so it could be parsed by pysam within VCFAnnotator.

Let me know what other info might be helpful
