### ISSUE TITLE
`n.` hgvs expressions are producing same output as `c.` expressions

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vrs-python#365]
Both 
```
NM_001331029.1:n.872A>G  and  NM_001331029.1:c.872A>G
(the first is a non-coding location on a dna sequence which is presumably using the full dna sequence to identify the location. the second is the coding sequence location or the 872nd postion after the start codon. two very different locations assuming the start codon is not the very first base in the dna sequence of course.)
```
as well as
```
NM_032446.3:c.*77C>T  and NM_032446.3:c.77C>T1
(both coding but the first is referencing 77 positions downstream of the 3` end past the stop codon. while the second it referencing the 77th position after the start codon. two very different locations.)
```
are producing the same VRS outputs (which is not correct)

There are a couple of concerns here. 
1. `n.` prefixes are meant ONLY for non-coding sequences. All `NM_` sequences are coding sequences and therefore should ONLY support `c.` prefixes.
2. `n.` sequences behave similar to the coordinate numbering as `g.` does on genomic sequences. They are 1-indexed position based representations. coding or `c.` numbering is more involved with `UTR` regions and the ability to indirectly references in intronic regions (which are not part of the actual coding sequence - making those specific cases infeasible to vrsify).
3.  If we were to allow `n.` on coding sequences, we would need to use a different approach and thus produce different output since the numbering of coding an non-coding positions (even on the same physical sequence) will always be different.

refseq uses NM_ sequences for protein coding RNA and should most likely always use `c.` positions for hgvs.  It is feasible someone could use `n.` on an NM_ but again the positions would be based on the full sequence and not on the start codon with specialized values for UTR regions.
Refseq uses NR_ for non-coding RNA, but it appears that hgvs recommends using `r.` prefix for RNA so there is no need for `n.` (since it is technically not DNA).  This is a bit confusing, but I assume there are non-coding dna sequences out there where it might be important to use `n.`. I'll defer to others to point that out, and specifically in the refseq database since this is our initial dataset that vrs-python is relying on through `biocommons.seqrepo`.

**Comment by larrybabb** [comment]
@korikuzma I would be interested on your feedback/analysis on this. can you verify if the underlying logic in biocommons.hgvs (which I presume is being utilized) is involved in determining the mapping between coding `c.` positions and the physical positions on the NM_ sequences that need to end up in the VRS output?  This could be a significant issue if it is not understanding how to map between `c.` positions in hgvs and physical positions on the sequence.

**Comment by korikuzma** [comment]
@larrybabb let me look more into this tomorrow if that’s ok
