### ISSUE TITLE
Transform variations to previous VRS version

### ISSUE THREAD

**Issue by jsstevenson** [ga4gh/vrs-python#382]
We (me, @jarbesfeld) have been refactoring a mapping pipeline, which previously created VRS 1.3 alleles and haplotypes, to use more up-to-date tooling. This means we're programmatically tied to VRS 2a, but we still need to create VRS 1.3 objects eventually. What we'd like to do is write something like a `.to_version(1.3)` method that produces an equivalent instance of a variation to comply with an older schema (where such equivalences are possible).

We are operating on a pretty quick turnaround time to hit a paper submission, so we'd like to write up what we need soon, but there is a lot of room for bigger conversations about how to expand tooling like this in the future.

**Comment by korikuzma** [comment]
https://github.com/ave-dcd/dcd_mapping/blob/main/src/dcd_mapping/annotate.py#L49
