### ISSUE TITLE
Implement cat-vrs (?)

### ISSUE THREAD

**Issue by theferrit32** [ga4gh/vrs-python#410]
Should we add cat-vrs classes to `ga4gh.vrs.models` or maybe under a different one in vrs-python (e.g. `ga4gh.cat_vrs.models`)

**Comment by korikuzma** [comment]
@theferrit32 we will be migrating pydantic models to https://github.com/ga4gh/gks-validator. This is so that we can have all pydantic models in one place

**Comment by korikuzma** [comment]
@theferrit32 actually I realized this won't be the best idea because of versioning with different specs. I think we should create separate repos for each spec. What do you think?

**Comment by korikuzma** [comment]
Closing. Doing this in https://github.com/ga4gh/cat-vrs-python repo.
