### ISSUE TITLE
Write Quick Start Guide

### ISSUE THREAD

**Issue by reece** [ga4gh/vrs-python#43]
@melissacline recommended a quick start guide for using VRS and vr-python. For now, I'll park that request here in vr-python, but it might be that the notebooks or documentation should migrate to vr-spec. We can decide that later.

**Comment by zicale** [comment]
I want to solve this issue.

**Comment by reece** [comment]
Yay! I would be happy to work with you, if that's useful.
One way to start might be to propose an outline and post here.
If you happen to have started already, feel free to share a branch (on your own fork) or even a draft PR if you're that far along.
