### ISSUE TITLE
Object types return ENUM instead of ENUM.value

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vrs-python#433]
When running the Jupyter notebooks, I noticed that VRS objects are being returned with what looks like an ENUM entry for the object type field:

<img width="687" alt="image" src="https://github.com/user-attachments/assets/3e365a02-1e7d-44d3-8df3-5ada33b24f2b">

Instead, we expect these to be specified by enum.value:

<img width="684" alt="image" src="https://github.com/user-attachments/assets/235a0cfa-265b-4c04-82ec-a0088495fafd">

**Comment by jsstevenson** [comment]
Is there a need to build this behavior into model_dump rather than reserving model_dump_json (https://docs.pydantic.dev/latest/concepts/serialization/#modelmodel_dump_json) for this?

**Comment by ahwagner** [comment]
I'm not sure about that–I think this has to do with what gets populated in the model, not how it is serialized.
