### ISSUE TITLE
AlleleTranslator import error

### ISSUE THREAD

**Issue by smoudour** [ga4gh/vrs-python#439]
New user here trying to grasp the vrs toolkit concept. I'm using conda environment inside WSL.

I have installed the vrs-python module using the designated recipe: 
`sudo apt install gcc libpq-dev`

I left out the python-dev as conda python builds already include the headers, so a separate python-dev package doesn't appear necessary.

Then, as starters, I'm trying to run the [notebooks quickstart code](https://github.com/ga4gh/vrs-python/blob/main/notebooks/getting_started/1_Quick_Start.ipynb). When trying to import the allele translator, I get an error, see below:

`from ga4gh.vrs.extras.translator import AlleleTranslator`
`ImportError: cannot import name 'AlleleTranslator' from 'ga4gh.vrs.extras.translator'`

Any ideas what I'm doing wrong?

**Comment by korikuzma** [comment]
@smoudour Hi, have you installed the notebook dependencies? `pip install -e '.[extras,notebooks]'`

https://github.com/ga4gh/vrs-python/tree/main/notebooks/getting_started#setup-vrs-python

**Comment by smoudour** [comment]
Hi 
@korikuzma thanks for the prompt reply.

I installed vrs-python using 
`pip install 'ga4gh.vrs[extras]'`
inside my conda env.

**Comment by korikuzma** [comment]
@smoudour what version of VRS-Python are you using? `pip freeze | grep ga4gh.vrs`

**Comment by smoudour** [comment]
@korikuzma ga4gh.vrs==0.8.5

**Comment by korikuzma** [comment]
@smoudour Ah, so the notebooks on `main` branch work for the latest alpha release (2.0.0-a10). Please use the notebooks found here: https://github.com/ga4gh/vrs-python/tree/0.8.5 for 0.8.5

**Comment by korikuzma** [comment]
`main` branch uses draft VRS 2.0, whereas `0.8.5` uses VRS 1.3 models.

**Comment by jsstevenson** [comment]
@smoudour alternatively, install the latest VRS-Python release:

`pip install 'ga4gh.vrs[extras]==2.0.0-a10'

We should probably update installation instructions accordingly
