### ISSUE TITLE
SimpleInterval and SequenceState use in Translator

### ISSUE THREAD

**Issue by sawmonaco** [ga4gh/vrs-python#69]
I'm in the process of upgrading from 0.6.4 to 0.7.2. I wanted to use SequenceInterval, as SimpleInterval is deprecated. I ran into an issue using the translator, however, as it doesn't yet support SequenceInterval ([tests showing current parse behavior](https://github.com/ga4gh/vrs-python/blob/7814f55676d4f752a16dcf02dccb435593cffe81/tests/extras/test_translator.py#L48)). 

I'm happy to put in a PR to upgrade the translator to use the SequenceInterval when parsing HGVS to Allele, and supporting either the SimpleInterval or SequenceInterval when parsing from Allele to HGVS string.

Are there any other considerations here?

**Comment by sawmonaco** [comment]
It looks like SequenceState is also deprecated, so the translator should use LiteralSequenceExpression instead as well?

**Comment by korikuzma** [comment]
Hi @sawmonaco , thanks for pointing this out. I am working on creating a PR for this now. We'll just have to replace `SimpleInterval` with `SequenceInterval` and `SequenceState` with `LiteralSequenceExpression`.

**Comment by sawmonaco** [comment]
Thanks for the quick turnaround!
