### ISSUE TITLE
Some transcripts raising HGVSDataNotAvailableError during translation from allele -> HGVS

### ISSUE THREAD

**Issue by sawmonaco** [ga4gh/vrs-python#73]
I'm attempting to translate from an Allele representation back to a transcript representation and am running receiving errors like `HGVSDataNotAvailableError: No mapping info available for XM_017001344.1` for a few of the transcripts. I believe this is because of the way we loop through all of the aliases when translating to HGVS. 

https://github.com/ga4gh/vrs-python/blob/4978e88396c8a718576ade805c8b1332b7108496/src/ga4gh/vrs/extras/translator.py#L381-L395

The specific case for `XM_017001344.1` is hit when I have an allele using `NM_001331029.1`. The `XM_017001344.1` alias is returned as well as the expected `NM_001331029.1` by `get_metadata` for the `refseq` namespace. 

```
data_proxy.get_metadata("NM_001331029.1")

{'length': 11291,
 'alphabet': 'ACGT',
 'added': '2016-08-24T05:03:40Z',
 'aliases': ['MD5:a8d7243ffeea4ade1dbc33613887693b',
  'NCBI:NM_001331029.1',
  'refseq:NM_001331029.1',
  'NCBI:XM_017001344.1',
  'refseq:XM_017001344.1',
  ...]}
```

I was thinking one possible solution is to wrap the normalization in a try/except block. Then, if an HGVSDataNotAvailableError is raised, we can catch it and log a warning, without stopping execution flow. This way, the other aliases will still return an HGVS string value.

I am happy to put in a PR, but what do you think of the approach?

**Comment by reece** [comment]
Hi @sawmonaco -- Thanks for raising this and for taking the time to post the question so clearly.

Yes, I think your proposal is the first step. If you're game for submitting a PR, fabulous!

As an optimization, you could also filter aliases for suffixes that we know that we can handle around line 387 with something like `if not(any(a.startswith(pfx) for pfx in ("NM", "NP", "NC", ...)): continue`. This will prevent us from tackling accessions that we know we can't handle.
