### ISSUE TITLE
Don't specify type when redundant to instanciated class

### ISSUE THREAD

**Issue by andreasprlic** [ga4gh/vrs-python#88]
It looks as if right now we need to write 

```models.IndefiniteRange(type="IndefiniteRange", value=1, comparator="<=")```

when the following would be much cleaner

```models.IndefiniteRange(value=1, comparator="<=")```

Can we just assume that the type matches the instantiated class, unless specified differently?

**Comment by korikuzma** [comment]
@andreasprlic This is an issue I was encountering on my machine (macOS, Intel) but @jsstevenson was not encountering this issue somehow.

**Comment by reece** [comment]
The typical behavior, and certainly the intent, is that you shouldn't specify type in the args. This should be handled by the model itself.

@ahwagner  proposed changing the type enum to a static. Did that ever happen? Perhaps that's related?

@andreasprlic : What happens with `models.IndefiniteRange(value=1, comparator="<=")`? 

Not only should you not specify the type in the args, it should be an error (and may be) if you specify anything other than that type.

**Comment by jsstevenson** [comment]
I just recreated a fresh environment (like very fresh, deleted my python installation) and am now able to reproduce this:

```
In [2]: models.IndefiniteRange(value=1, comparator="<=")
Out[2]: <IndefiniteRange comparator=<Literal<str> <=> type=None value=<Literal<int> 1>>

In [3]: models.IndefiniteRange(value=1, comparator="<=", type="fake_type")
Out[3]: <IndefiniteRange comparator=<Literal<str> <=> type=<Literal<str> fake_type> value=<Literal<int> 1>>

In [4]: models.IndefiniteRange(value=1, comparator="<=", type="IndefiniteRange")
Out[4]: <IndefiniteRange comparator=<Literal<str> <=> type=<Literal<str> IndefiniteRange> value=<Literal<int> 1>>

In [5]: import python_jsonschema_objects as pjs

In [6]: pjs.__version__
Out[6]: '0.4.1'
```

**Comment by korikuzma** [comment]
@jsstevenson You are right. It affects `ga4gh_identify` + translator methods.

@reece I think you are also right. Looks like we switched from using `enum` to `const`. It also appears that we used to set a `default` value for the type which may also be the cause of this.

**Comment by korikuzma** [comment]
@reece @andreasprlic @jsstevenson Can confirm. Adding `default` fixes the ValidationError. I can create a PR in VRS for this.
