### ISSUE TITLE
Represent ISCN Absolute Copy Number Variation

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/vrs-python#94]
Requested by @larrybabb for their work

**Comment by korikuzma** [comment]
https://www.ncbi.nlm.nih.gov/clinvar?term=((%22copy%20number%20gain%22%5BType%20of%20variation%5D%20OR%20%22copy%20number%20loss%22%5BType%20of%20variation%5D

**Comment by larrybabb** [comment]
Great. One thing I noticed is that ClinVar does have some occurrences of NCBI36/hg18 ISCN CNVs. Do we have the ability to generate variants against NCBI36/hg18 reference sequences? 
If not, we will need to drop these variants in the `TextVariation` bucket I presume. Something to discuss.

**Comment by korikuzma** [comment]
Closing since we're going a different route of parsing components. If we want to follow clinvar syntax, we can re-open.
