### ISSUE TITLE
problem with "install dependencies for ga4gh.vrs.extras"

### ISSUE THREAD

**Issue by delongmeng** [ga4gh/vrs-python#96]
Hello, 
I'm trying to use vrs-python and not sure if I correctly followed the instruction for "install dependencies for ga4gh.vrs.extras":

> <img width="769" alt="image" src="https://user-images.githubusercontent.com/51895412/165630652-a276b43e-b304-4c9d-b0f1-b29393d1c208.png">

**What I did:**

I set up a virtual environment and used `pip install ga4gh.vrs[extras]` to install packages.

Then I ran these 3 commands:
```
$ docker volume create --name=uta_vol
$ docker volume create --name=seqrepo_vol
$ docker-compose up
```
and got:
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/51895412/165632132-49d15a07-58b2-432f-b3de-4eee66555da0.png">
(don't know if this is expected)

I guess this (from the instruction) is not a valid command to run: 
> `$ docker ps CONTAINER ID IMAGE // NAMES 86e872ab0c69 biocommons/seqrepo-rest-service:latest // vrs-python_seqrepo-rest-service_1 a40576b8cf1f biocommons/uta:uta_20180821 // vrs-python_uta_1`

So I ran `docker ps` and can see 2 containers:
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/51895412/165631503-67632e1b-a075-408d-9fc2-d84abaa26f40.png">

Then I followed the instruction to "test UTA and seqrepo installations" (don't know what "snafu" is in the instruction):
`psql -XAt postgres://anonymous@localhost:5000/uta -c 'select count(*) from transcript'` and got error:

<img width="685" alt="image" src="https://user-images.githubusercontent.com/51895412/165631818-73b5d8cb-2e99-41fa-a038-07a95097b597.png">

I'd like to use the translator functionality as demonstrated in the notebook (vrs-python/notebooks/Extras.ipynb) and I got this:

<img width="1521" alt="image" src="https://user-images.githubusercontent.com/51895412/165632575-b404da3f-1bd3-417e-b0aa-d0bed6ef786d.png">

I believe this is because I didn't install seqrepo correctly. 

Could I get some help regarding how to set up the dependencies to use vrs-python?

Thanks,
Delong

**Comment by korikuzma** [comment]
Hi @delongmeng , 

Sorry about the issues you're encountering. Several new members have joined our team and are encountering similar installation issues, which is one main reason why we're currently working on #93 . 

I had to configure the docker-compose.yaml as seen in [this](https://github.com/ga4gh/vrs-python/issues/61#issuecomment-1111605187) comment. It does allow you to run the `psql -XAt postgres://anonymous@localhost/uta -c 'select count(*) from transcript'` command. I, personally, use [Docker Desktop ](https://www.docker.com/products/docker-desktop/) and use the `vrs-python_uta_1` CLI to run the command. However, the reconfigured docker-compose.yaml does get the same OSError as seen in #61. I'm hoping @reece will be able to assist with this issue. 

As for the OSError in the notebook, this is due to the difference between `SeqRepoDataProxy` (local instance of SeqRepo) and `SeqRepoRestDataProxy` (REST instance of SeqRepo). When using `SeqRepoDataProxy` (as shown in the notebook example), I would follow the quick start instructions found [here](https://github.com/biocommons/biocommons.seqrepo#quick-start).

**Comment by delongmeng** [comment]
> Hi @delongmeng ,
> 
> Sorry about the issues you're encountering. Several new members have joined our team and are encountering similar installation issues, which is one main reason why we're currently working on #93 .
> 
> I had to configure the docker-compose.yaml as seen in [this](https://github.com/ga4gh/vrs-python/issues/61#issuecomment-1111605187) comment. It does allow you to run the `psql -XAt postgres://anonymous@localhost/uta -c 'select count(*) from transcript'` command. I, personally, use [Docker Desktop ](https://www.docker.com/products/docker-desktop/) and use the `vrs-python_uta_1` CLI to run the command. However, the reconfigured docker-compose.yaml does get the same OSError as seen in #61. I'm hoping @reece will be able to assist with this issue.
> 
> As for the OSError in the notebook, this is due to the difference between `SeqRepoDataProxy` (local instance of SeqRepo) and `SeqRepoRestDataProxy` (REST instance of SeqRepo). When using `SeqRepoDataProxy` (as shown in the notebook example), I would follow the quick start instructions found [here](https://github.com/biocommons/biocommons.seqrepo#quick-start).

**Comment by delongmeng** [comment]
Sorry I accidentally closed this. Will reopen now.

@korikuzma 
Thanks for your reply! I'll try the configurations that you suggested and keep you updated!

**Comment by delongmeng** [comment]
@korikuzma 
I modified the .yaml file as you suggested and now have exactly the same observation as in #61 (as you also mentioned: can run the psql command and get the result, but still get the same OSError). So it seems like the API is still not working, right? I still don't fully understand what the problem is though, like why it says "Unable to open SeqRepo directory /usr/local/share/seqrepo/latest", is that directory the one on my local machine (client side) or on the server (I guess the server is also in my local machine but in the volume of the container? I'm not sure...)?

To use the functionality in Jupyter Notebook, I guess if I understand it correctly, I will want to install SeqRepo in my local machine so it's a local instance of SeqRepo? I try to follow the quick start instruction link you provided, but I see that it is for "Ubuntu 16.04". Do you know if there is a Mac OS version so I can run it on my local machine? Thanks!

**Comment by delongmeng** [comment]
Update: 
I followed the instruction in the `biocommons.seqrepo` repo to install seqrepo on my local machine (Mac OS). 
1. Checked that I have sqlite3:
```
$ sqlite3 --version
3.32.3 2020-06-18 14:16:19 02c344aceaea0d177dd42e62c8541e3cab4a26c757ba33b3a31a43ccc7d4aapl
```

2. installed tabix
```
$ tabix

Program: tabix (TAB-delimited file InderXer)
Version: 0.2.5 (r1005)

Usage:   tabix <in.tab.bgz> [region1 [region2 [...]]]

Options: -p STR     preset: gff, bed, sam, vcf, psltbl [gff]
         -s INT     sequence name column [1]
         -b INT     start column [4]
         -e INT     end column; can be identical to '-b' [5]
         -S INT     skip first INT lines [0]
         -c CHAR    symbol for comment/meta lines [#]
         -r FILE    replace the header with the content of FILE [null]
         -B         region1 is a BED file (entire file will be read)
         -0         zero-based coordinate
         -h         print also the header lines
         -H         print only the header lines
         -l         list chromosome names
         -f         force to overwrite the index
```

3.  Installed seqrepo and fetched data:

```
$ pip install seqrepo
$ sudo mkdir /usr/local/share/seqrepo
$ sudo chown $USER /usr/local/share/seqrepo
$ seqrepo pull -i 2018-11-26
# got error "PermissionError: [Errno 13] Permission denied: '/usr/local/share/seqrepo/2018-11-26.s2df630r' -> '/usr/local/share/seqrepo/2018-11-26'"
# so I manually did the rename step:
$ sudo mv /usr/local/share/seqrepo/2018-11-26.s2df630r /usr/local/share/seqrepo/2018-11-26
```

It looks like it was successful:
```
$ seqrepo show-status -i 2018-11-26
seqrepo 0.6.5
instance directory: /usr/local/share/seqrepo/2018-11-26, 11.3 GB
backends: fastadir (schema 1), seqaliasdb (schema 1) 
sequences: 841931 sequences, 102777417560 residues, 268 files
aliases: 9697847 aliases, 9344237 current, 48 namespaces, 841931 sequences
```
and the seqrepo shell is working:
```
$ seqrepo start-shell -i 2018-11-26
Python 3.8.10 (default, Nov 11 2021, 09:48:35) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.2.0 -- An enhanced Interactive Python. Type '?' for help.

seqrepo (https://github.com/biocommons/biocommons.seqrepo/)
version: 0.6.5
instance path: /usr/local/share/seqrepo/2018-11-26

In [1]: sr["NC_000001.11"][780000:780020]
Out[1]: 'TGGTGGCACGCGCTTGTAGT'
```

**Problem**
But I still have problem using it in Python (either in the terminal or through Jupyter Notebook): 

```
$ python
Python 3.8.10 (default, Nov 11 2021, 09:48:35) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from biocommons.seqrepo import SeqRepo
>>> sr = SeqRepo("/usr/local/share/seqrepo/latest")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/delong.meng/venv/vrs/lib/python3.8/site-packages/biocommons/seqrepo/seqrepo.py", line 114, in __init__
    self.sequences = FastaDir(self._seq_path, writeable=self._writeable, check_same_thread=self._check_same_thread)
  File "/Users/delong.meng/venv/vrs/lib/python3.8/site-packages/biocommons/seqrepo/fastadir/fastadir.py", line 68, in __init__
    self._db = sqlite3.connect(self._db_path,
sqlite3.OperationalError: unable to open database file
>>> 
```

Got the "sqlite3.OperationalError: unable to open database file" error.

Any idea why this happens and how to solve it? (I feel I'm very close to make it work now.) @korikuzma

**Comment by korikuzma** [comment]
Hi @delongmeng ,

I want to say that the OSError in #61 is caused by the biocommons image, but I'm not sure. I'm not the best with Docker. 

In your terminal, I would run `seqrepo update-latest`, this will create a symlink and have latest pointing to the 2018-11-26 version. The README for SeqRepo is outdated, the latest version is 2021-01-29. I would recommend pulling again to fetch the latest version. Then running `seqrepo update-latest` should work. 

Please let me know if this fixes your error.

**Comment by delongmeng** [comment]
Thanks!! @korikuzma 
Yes I've just figured out exactly the same reason that you mentioned haha!! I didn't know I could directly run `seqrepo update-latest`, but from the script and through some debugging process, I realized I need to create the symlink. I manually ran this command `ln -s /usr/local/share/seqrepo/2018-11-26 /usr/local/share/seqrepo/latest` and it worked!

Good to know that the latest version is 2021-01-29. I'll definitely upgrade to that version.
Anyway, thanks a lot for help! Everything seems to be working now!


> Hi @delongmeng ,
> 
> I want to say that the OSError in #61 is caused by the biocommons image, but I'm not sure. I'm not the best with Docker.
> 
> In your terminal, I would run `seqrepo update-latest`, this will create a symlink and have latest pointing to the 2018-11-26 version. The README for SeqRepo is outdated, the latest version is 2021-01-29. I would recommend pulling again to fetch the latest version. Then running `seqrepo update-latest` should work.
> 
> Please let me know if this fixes your error.

**Comment by delongmeng** [comment]
BTW, I have a minor question: does the version of seqrepo affect the IDs generated by VRS-python? Let's say I generated all IDs for my variations based on seqrepo 2018-11-26, then one day I upgrade seqrepo to 2021-01-29, do I need to re-generate all of the IDs that I previously generated? Is it possible that the VRS IDs for some variations can become different? @korikuzma

**Comment by korikuzma** [comment]
Hi @delongmeng ,

I'm so happy to hear that things are working now! 😄 The installation process is quite complicated and our team is looking to improve this for users. 

If you want to see all SeqRepo releases you can run: `seqrepo list-remote-instances`.

From the [SeqRepo manuscript](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7714221/):

> Sequences in SeqRepo are immutable and not deletable; therefore, sequence files never change and exist in all future SeqRepo snapshots. New releases require only the space for new sequences and manifest db.

So as long as you are using the same accession and version, you will not have to regenerate your VRS digests if you are translating nomenclatures such as HGVS and SPDI since they use accessions. However, with gnomAD and Beacon which take chromosome instead of accession, you should be sure to specify the `assembly_name` in the method ([beacon method](https://github.com/ga4gh/vrs-python/blob/main/src/ga4gh/vrs/extras/translator.py#L109) and [gnomAD method](https://github.com/ga4gh/vrs-python/blob/main/src/ga4gh/vrs/extras/translator.py#L151)). If you do not specify, it will use the GRCh38 assembly.

**Comment by delongmeng** [comment]
@korikuzma 

Thank you for the explanation! That's very clear and helpful! Now I've set up the environment, I can finally play with the actual ID generation process!

Just to add some more information regarding the API. After I installed seqrepo, I tested the API (**run from the container**) again, and it still gave me the same error (the OSError), and I think it might be because it tries to open that path within the container but there's just nothing there (within the container). I feel it might be something regarding the "seqrepo_vol:/usr/local/share/seqrepo" settings? If my local path (which now has the database) is mounted to the container then it should be able to get the data?

I then tried the seqrepo API to connect to the server **running on my local machine** (I installed it following this repo: https://github.com/biocommons/seqrepo-rest-service), and now it works!! I was able to ping the server! And this test `curl http://localhost:5000/seqrepo/1/sequence/refseq:NM_000551.3` also returns me the sequence. 

I also tried this code snippet from one of the notebooks (using the `SeqRepoRESTDataProxy`) and it also worked:
```
from ga4gh.vrs.dataproxy import SeqRepoRESTDataProxy
seqrepo_rest_service_url = "http://localhost:5000/seqrepo"
dp = SeqRepoRESTDataProxy(base_url=seqrepo_rest_service_url)
```
The `psql` test didn't work this time, and this is expected because I didn't install uta on my local machine (I think I don't need it?).

So yeah, in conclusion, after installing seqrepo and the REST service on my local machine, I can have access to the data using either `SeqRepoDataProxy` or `SeqRepoRESTDataProxy` (through the API)! And I feel that the reason that the container is not working is because it doesn't have data (the sqlite database) in it. For an user to use it without having to install seqrepo locally, you may need to run the server somewhere and provide an endpoint (yeah, I think that's the goal of #93). Please feel free to close this issue if you'd like!
